# Generated by Django 5.2.13 on 2026-04-23 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=60)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('distrito', models.CharField(blank=True, default='', max_length=120)),
                ('contacto', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('hogar', 'Hogar'), ('gobierno', 'Gobierno'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='clientes.cliente')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('cliente', 'numero')},
            },
        ),
    ]
