# Generated by Django 5.1.7 on 2026-03-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('hogar', 'Hogar'), ('gobierno', 'Gobierno'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='clientes.cliente')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('cliente', 'numero')},
            },
        ),
    ]
