# Generated by Django 5.2.13 on 2026-04-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_cuenta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
