# Generated by Django 5.2.13 on 2026-04-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_cuenta_contacto_cuenta_direccion_cuenta_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='distrito',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
