# Generated by Django 5.2.13 on 2026-04-19 06:57

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_add_coordenadas_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
