# Generated by Django 5.2.13 on 2026-04-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cuentas', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_servicio', models.CharField(max_length=80)),
                ('zona', models.CharField(max_length=80)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=10)),
                ('fase', models.CharField(choices=[('creacion', 'Creacion'), ('programacion', 'Programacion'), ('seguimiento', 'Seguimiento'), ('cierre', 'Cierre')], default='creacion', max_length=20)),
                ('status_operativo', models.CharField(choices=[('por-confirmar', 'Por confirmar'), ('confirmado', 'Confirmado'), ('en-labor', 'En labor'), ('cierre-tecnico', 'Cierre tecnico'), ('facturacion', 'Facturacion'), ('completado', 'Completado'), ('dado-de-baja', 'Dado de baja')], default='por-confirmar', max_length=20)),
                ('subfase_tecnica', models.CharField(choices=[('confirmacion', 'Confirmacion'), ('ejecucion', 'Ejecucion'), ('evidencias', 'Evidencias'), ('cierre-tecnico', 'Cierre tecnico'), ('facturacion', 'Facturacion')], default='confirmacion', max_length=20)),
                ('diagnostico_tecnico', models.TextField(blank=True)),
                ('historial', models.JSONField(blank=True, default=list)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_labor', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_labor', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cuentas.cuenta')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='tecnicos.tecnico')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformeTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_final', models.TextField()),
                ('responsable_local', models.CharField(blank=True, max_length=150)),
                ('pedido_solicitado', models.CharField(blank=True, max_length=180)),
                ('observaciones', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('firma_cliente', models.FileField(upload_to='firmas/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_tecnicos', to='tecnicos.tecnico')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_tecnico', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/%d/')),
                ('descripcion', models.TextField()),
                ('stage', models.CharField(choices=[('antes', 'Antes'), ('despues', 'Despues')], max_length=12)),
                ('source', models.CharField(choices=[('archivo', 'Archivo'), ('camara', 'Camara')], default='archivo', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='tecnicos.tecnico')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(choices=[('materiales-listos', 'Materiales listos'), ('llegada-sitio', 'Llegada al sitio'), ('inicio-trabajo', 'Inicio de trabajo'), ('nota-adicional', 'Nota adicional')], max_length=30)),
                ('completado', models.BooleanField(default=False)),
                ('nota', models.TextField(blank=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_steps', to='tecnicos.tecnico')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_steps', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TecnicoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('nuevo_estado', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_updates', to='pedidos.pedido')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones', to='tecnicos.tecnico')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fase'], name='pedidos_ped_fase_f0f3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status_operativo'], name='pedidos_ped_status__73ce4e_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['tecnico_asignado'], name='pedidos_ped_tecnico_b736eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststep',
            unique_together={('pedido', 'step_id')},
        ),
    ]
