# Generated by Django 5.1.7 on 2026-04-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
        ("tecnicos", "0002_tecnico_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="diagnostico_tecnico",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_fin_labor",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_inicio_labor",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="historial",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pedido",
            name="status_operativo",
            field=models.CharField(
                choices=[
                    ("por-confirmar", "Por confirmar"),
                    ("confirmado", "Confirmado"),
                    ("en-labor", "En labor"),
                    ("cierre-tecnico", "Cierre tecnico"),
                    ("facturacion", "Facturacion"),
                    ("completado", "Completado"),
                ],
                default="por-confirmar",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="subfase_tecnica",
            field=models.CharField(
                choices=[
                    ("confirmacion", "Confirmacion"),
                    ("ejecucion", "Ejecucion"),
                    ("evidencias", "Evidencias"),
                    ("cierre-tecnico", "Cierre tecnico"),
                    ("facturacion", "Facturacion"),
                ],
                default="confirmacion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("media", "Media"),
                    ("alta", "Alta"),
                    ("critica", "Critica"),
                ],
                default="media",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ChecklistStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "step_id",
                    models.CharField(
                        choices=[
                            ("materiales-listos", "Materiales listos"),
                            ("llegada-sitio", "Llegada al sitio"),
                            ("inicio-trabajo", "Inicio de trabajo"),
                            ("nota-adicional", "Nota adicional"),
                        ],
                        max_length=30,
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                ("nota", models.TextField(blank=True)),
                ("completado_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_steps",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_steps",
                        to="tecnicos.tecnico",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(blank=True, max_length=255)),
                ("archivo", models.FileField(upload_to="evidencias/%Y/%m/%d/")),
                ("descripcion", models.TextField()),
                ("stage", models.CharField(choices=[("antes", "Antes"), ("despues", "Despues")], max_length=12)),
                (
                    "source",
                    models.CharField(
                        choices=[("archivo", "Archivo"), ("camara", "Camara")],
                        default="archivo",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidencias",
                        to="tecnicos.tecnico",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="InformeTecnico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("diagnostico_final", models.TextField()),
                ("responsable_local", models.CharField(blank=True, max_length=150)),
                ("pedido_solicitado", models.CharField(blank=True, max_length=180)),
                ("observaciones", models.TextField()),
                ("recomendaciones", models.TextField()),
                ("firma_cliente", models.FileField(upload_to="firmas/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informe_tecnico",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="informes_tecnicos",
                        to="tecnicos.tecnico",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TecnicoUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nota", models.TextField()),
                ("nuevo_estado", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tecnico_updates",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actualizaciones",
                        to="tecnicos.tecnico",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="checkliststep",
            unique_together={("pedido", "step_id")},
        ),
    ]
