# Generated by Django 5.2.13 on 2026-04-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_checkliststep_id_alter_evidencia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_operativo',
            field=models.CharField(choices=[('por-confirmar', 'Por confirmar'), ('confirmado', 'Confirmado'), ('en-labor', 'En labor'), ('cierre-tecnico', 'Cierre tecnico'), ('facturacion', 'Facturacion'), ('completado', 'Completado'), ('dado-de-baja', 'Dado de baja')], default='por-confirmar', max_length=20),
        ),
    ]
